[package]
name = "mcp2003a"
authors = ["Zach Grimaldi"]
description = "Rust no_std LIN Bus communication using the MCP2003A LIN transceiver."
version = "0.0.2"
edition = "2021"
license = "MIT"

[dependencies]
embedded-hal = "1.0.0"
embedded-io = "0.6.1"
